# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-15 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mogujie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='商品名')),
                ('trade_item_id', models.IntegerField(verbose_name='商品ID')),
                ('price', models.CharField(max_length=50, verbose_name='价格')),
                ('org_price', models.CharField(max_length=50, verbose_name='原价')),
                ('sale', models.CharField(max_length=50, verbose_name='销量')),
                ('img', models.ImageField(upload_to='mogujie', verbose_name='图片')),
                ('link', models.URLField(max_length=300, verbose_name='详情链接')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '蘑菇街',
                'db_table': 'mogujie',
                'verbose_name': '蘑菇街',
            },
        ),
        migrations.AlterIndexTogether(
            name='mogujie',
            index_together=set([('title', 'trade_item_id')]),
        ),
    ]
