# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-15 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mogujie',
            name='trade_item_id',
            field=models.CharField(max_length=50, verbose_name='商品ID'),
        ),
    ]
